---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: node
    tag: 16

inputs:
  - name: fauna-vscode-repository

run:
  path: ./fauna-vscode-repository/concourse/scripts/unit-tests.sh
